export enum NotificationType {
  ORDER_CONFIRMED = 'order_confirmed',
  ORDER_ACCEPTED = 'order_accepted',
  ORDER_PREPARING = 'order_preparing',
  ORDER_BAKING = 'order_baking',
  ORDER_OUT_FOR_DELIVERY = 'order_out_for_delivery',
  DRIVER_ARRIVING = 'driver_arriving',
  ORDER_DELIVERED = 'order_delivered',
  ORDER_PACKING = 'order_packing',
  ORDER_READY = 'order_ready',
  ORDER_COMPLETED = 'order_completed',
  ORDER_CANCELLED = 'order_cancelled',
  ORDER_REJECTED = 'order_rejected',
  NEW_ORDER_ADMIN = 'new_order_admin',
  ORDER_CANCELLED_ADMIN = 'order_cancelled_admin',
  DELIVERY_ASSIGNED = 'delivery_assigned',
  PROMOTION = 'promotion',
  DISCOUNT = 'discount',
  COUPON_EXPIRING = 'coupon_expiring',
  SUPPORT_REPLY = 'support_reply',
  SUPPORT_CUSTOMER_MESSAGE = 'support_customer_message',
  SUPPORT_TICKET_ASSIGNED = 'support_ticket_assigned',
  SUPPORT_STATUS_CHANGED = 'support_status_changed',
  SYSTEM = 'system',
}
