export enum OrderStatus {
  PENDING_PAYMENT = 'pending_payment',
  PLACED = 'placed',
  ACCEPTED = 'accepted',
  PREPARING = 'preparing',
  BAKING = 'baking',
  PACKING = 'packing',
  READY = 'ready',
  DRIVER_ASSIGNED = 'driver_assigned',
  OUT_FOR_DELIVERY = 'out_for_delivery',
  DELIVERED = 'delivered',
  CLOSED = 'closed',
  CANCELLED = 'cancelled',
  REJECTED = 'rejected',
}
